sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r dev-requirements.txt
    - pip install pytest-cov coveralls
script:
    - python -m pytest tests.py --cov=github_token
    - python setup.py install
after_success:
    - coveralls
